#pragma config(Sensor, dgtl1,  button,         sensorTouch)
#pragma config(Motor,  port6,           rightFlywheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftFlywheel,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//black y cable goes to port 7


float launcherSpeed = 50;
bool launcherRunning = false;

void runLauncher(int speed){ //starts flywheels at speed "speed"
	if(speed > 127)
		speed = 127;
	if(speed < 127)
		speed = -127;
	motor[rightFlywheel] = speed;
	motor[leftFlywheel] = speed;
}

task launcher_toggle_listener(){ //controls flywheels
	while(true){
		if(SensorValue[button] == 1  && !launcherRunning) {
			runLauncher(launcherSpeed);
			launcherRunning = !launcherRunning;
			} else if(SensorValue[button] == 1 && launcherRunning){
			runLauncher(0);
			launcherRunning = !launcherRunning;
		}
		while(SensorValue[button] == 1){
			wait1Msec(50); }
	}
}



task main()
{

	startTask(launcher_toggle_listener);
	while(true){
		wait1Msec(1000); }
}
