#pragma config(Sensor, dgtl1,  button,         sensorTouch)
#pragma config(Sensor, dgtl2,  rightButton,    sensorTouch)
#pragma config(Sensor, dgtl3,  leftButton,     sensorTouch)
#pragma config(Motor,  port6,           rightFlywheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftFlywheel,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//black y cable goes to port 7


float launcherSpeed = 0;
bool launcherRunning = false;

void runLauncher(){ //starts flywheels at launcherSpeed "launcherSpeed"
	if(launcherSpeed > 127)
		launcherSpeed = 127;
	if(launcherSpeed < -127)
		launcherSpeed = -127;
	motor[rightFlywheel] = launcherSpeed;
	motor[leftFlywheel] = launcherSpeed;
}

void stopLauncher(){
	motor[rightFlywheel] = 0;
	motor[leftFlywheel] = 0;
}

task launcher_toggle_listener(){ //controls flywheels
	while(true){
		if(SensorValue[button] == 1  && !launcherRunning) {
			runLauncher();
			launcherRunning = !launcherRunning;
			while(SensorValue[button] == 1)
				wait1Msec(50);
			} else if(SensorValue[button] == 1 && launcherRunning){
			stopLauncher();
			launcherRunning = !launcherRunning;
			while(SensorValue[button] == 1)
				wait1Msec(50);
		}

	}
}

task launcher_launcherSpeed_control(){ //changes launcherSpeed of flywheels
	while(true){
		if(SensorValue[leftButton] == 1 && SensorValue[rightButton] == 0){
			launcherSpeed -= 12.7;
			while(SensorValue[leftButton] == 1)
				wait1Msec(25);
			} else if(SensorValue[leftButton] == 0 && SensorValue[rightButton] == 1){
			launcherSpeed += 12.7;
			while(SensorValue[rightButton] == 1)
				wait1Msec(25);
		}
		if(launcherRunning)
			runLauncher();
		wait1Msec(50);
	}
}


task main()
{

	startTask(launcher_toggle_listener);
	startTask(launcher_launcherSpeed_control);
	while(true){
		wait1Msec(1000); }
}
