#pragma config(Motor,  port2,           backRightMotor, tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontRightMotor, tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontLeftMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           backLeftMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           rightFlywheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftFlywheel,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intakeMotor,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!



float launcherSpeed = 127;
bool launcherRunning = false;

void runLauncher(){ //starts flywheels at launcherSpeed "launcherSpeed"
	if(launcherSpeed > 127)
		launcherSpeed = 127;
	if(launcherSpeed < -127)
		launcherSpeed = -127;
	motor[rightFlywheel] = launcherSpeed;
	motor[leftFlywheel] = launcherSpeed;
}

void stopLauncher(){
	motor[rightFlywheel] = 0;
	motor[leftFlywheel] = 0;
}

task launcher_toggle_listener(){ //controls flywheels
	while(true){
		if(vexRT[Btn8D] == 1  && !launcherRunning) {
			runLauncher();
			launcherRunning = !launcherRunning;
			while(vexRT[Btn8D] == 1)
				wait1Msec(50);
			} else if(vexRT[Btn8D] == 1 && launcherRunning){
			stopLauncher();
			launcherRunning = !launcherRunning;
			while(vexRT[Btn8D] == 1)
				wait1Msec(50);
		}
	}//end of while loop
}

task launcher_speed_control(){ //changes launcherSpeed of flywheels
	while(true){
		if(vexRT[Btn8L] == 1 && vexRT[Btn8R] == 0){
			launcherSpeed -= 12.7;
			while(vexRT[Btn8L] == 1)
				wait1Msec(25);
			} else if(vexRT[Btn8L] == 0 && vexRT[Btn8R] == 1){
			launcherSpeed += 12.7;
			while(vexRT[Btn8R] == 1)
				wait1Msec(25);
		}
		if(launcherRunning)
			runLauncher();
		wait1Msec(50);
	}//end of while loop
}

task motor_control{
	while(true){
		if((vexRT[Btn5U] == 0) == (vexRT[Btn6U] == 0) && (vexRT[Btn5D] == 0) == (vexRT[Btn6D] == 0)){ //normal driving controls
			motor[frontLeftMotor] = vexRT[Ch2];
			motor[backRightMotor] = vexRT[Ch2];
			motor[frontRightMotor] = vexRT[Ch3];
			motor[backLeftMotor] = vexRT[Ch3];
			} else if(vexRT[Btn6U] == 1) { //rotate left
			motor[frontLeftMotor] = 127;
			motor[backRightMotor] = -127;
			motor[frontRightMotor] = -127;
			motor[backLeftMotor] = 127;
			wait1Msec(40);
			} else if(vexRT[Btn5U] == 1){ //rotate right
			motor[frontLeftMotor] = -127;
			motor[backRightMotor] = 127;
			motor[frontRightMotor] = 127;
			motor[backLeftMotor] = -127;
			wait1Msec(40);
			} else if(vexRT[Btn5D] == 1){ //half speed right rotate
			motor[frontLeftMotor] = -40;
			motor[backRightMotor] =40;
			motor[frontRightMotor] =40;
			motor[backLeftMotor] = -40;
			wait1Msec(40);
			} else {//half speed left rotate
			motor[frontLeftMotor] =40;
			motor[backRightMotor] = -40;
			motor[frontRightMotor] = -40;
			motor[backLeftMotor] =40;
			wait1Msec(40);
		}
		wait1Msec(10);
	}//end of while loop
}


task intake_control(){ //controls intakes
	while(true){
		if(vexRT[Btn7U] == 1){
			motor[intakeMotor] = 127;
			while(vexRT[Btn7U] == 1)
				wait1Msec(50);
			while(vexRT[Btn7U] == 0)
				wait1Msec(50);
			} else if(vexRT[Btn7D] == 1){
			motor[intakeMotor] = -127;
			while(vexRT[Btn7D]== 1)
				wait1Msec(50);
			while(vexRT[Btn7D]== 0)
				wait1Msec(50);
		}
		motor[intakeMotor] = 0;
		while(vexRT[Btn7U] == 1 || vexRT[Btn7D] == 1)
			wait1Msec(50);
		wait1Msec(50);
	}
}





/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................
	launcherSpeed = 127;
	runLauncher();
	launcherRunning = true;
	wait(3);
	motor[intakeMotor] = 50;
	wait(10);
	motor[intakeMotor] = 0;
	stopLauncher();
	launcherRunning = false;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{

	startTask(launcher_toggle_listener);
	startTask(launcher_speed_control);
	startTask(motor_control);
	startTask(intake_control);
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................
		wait1Msec(100);
	}
}
